echo " ______                 _____ _                 _   _____                    "
echo "|___  /                /  __ \ |               | | |_   _|                   "
echo "   / /  ___ _   _ ___  | /  \/ | ___  _   _  __| |   | | ___  __ _ _ __ ___  "
echo "  / /  / _ \ | | / __| | |   | |/ _ \| | | |/ _  |   | |/ _ \/ _  | '_   _ \ "
echo "./ /__|  __/ |_| \__ \ | \__/\ | (_) | |_| | (_| |   | |  __/ (_| | | | | | |"
echo "\_____/\___|\__,_|___/  \____/_|\___/ \__,_|\__,_|   \_/\___|\__,_|_| |_| |_|"
echo ""
echo ""
echo "Kafka Producer Starter "
echo ""
echo ""
echo "You can run this either from your IDE or from command line."
echo "To run from command line, first build it using maven:"
echo "  mvn package"
echo "Once built maven will create the following jar - target/producer-0.0.1-SNAPSHOT.jar"
echo "Run that jar with the following command, but fill in your values username/password/dir instead"
echo "  java -jar target/producer-0.0.1-SNAPSHOT.jar --kafka.username=xxxxxx --kafka.password=xxxxx --writable.dir=/tmp"